apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-argo-test
  template:
    metadata:
      labels:
        app: nginx-argo-test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-argo-test
spec:
  selector:
    app: nginx-argo-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: nginx-test.ahsanjsdev.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-argo-test
                port:
                  number: 80
  # tls:
  #   - hosts:
  #       - ahsanjsdev.tech
  #     # secretName: tls-ahsanjsdev-tech
  #     secretName: nginx1
