apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: helloworld
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: helloworld
  namespace: helloworld
  annotations:
    external-dns.alpha.kubernetes.io/target: microk8s-metal.civilfleet.org
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`helloworld.civilfleet.org`)
      kind: Rule
      services:
        - name: helloworld
          port: 80
  tls: {}
