apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
data:
  api-token: "TWFycmxpSEtVUXp3NEhVbDdEZkREaTdIR1VIcUpHTGFNbnhQZmhfVQ==" # <-- Replace with your Cloudflare API token

# EHpw-PBcIHtqXQr0uokut2YEGcHKcdnVt1BNmBLp token from cloudflare
# TWFycmxpSEtVUXp3NEhVbDdEZkREaTdIR1VIcUpHTGFNbnhQZmhfVQ==
