# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-api-key-secret
#   namespace: cert-manager
# type: Opaque
# stringData:
#   email: ahsanjsdev@gmail.com
#   apiKey: eb271ed9a07b0b959804cf6e389390eb5b515
#   cloudflareAccount: your-cloudflare-account-id
#   cloudflareZone: your-cloudflare-zone-id

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
data:
  api-token: "TWFycmxpSEtVUXp3NEhVbDdEZkREaTdIR1VIcUpHTGFNbnhQZmhfVQ==" # <-- Replace with your Cloudflare API token

# EHpw-PBcIHtqXQr0uokut2YEGcHKcdnVt1BNmBLp token from cloudflare
# TWFycmxpSEtVUXp3NEhVbDdEZkREaTdIR1VIcUpHTGFNbnhQZmhfVQ==
